fragment PlayerParts on Player {
  id
  name
  auth
  conn
}

fragment StatisticsParts on Statistics {
  rank
  goals
  wins
  games
  assists
  points
  coins
  defeats
  owngoals
  draws
}

query UpsertPlayer($player: UpsertPlayerPlayerInput!, $roomState: UpsertPlayerRoomStateInput!) {
  entity: upsertPlayer(input: { player: $player, roomState: $roomState }) {
    player: player {
      ...PlayerParts
    }

    state: roomState {
      room
      role
      items {
        ... on ColorType {
          type
          value
        }
      }
      statistics {
        ...StatisticsParts
      }
    }
  }
}
